version: '3'
services:
  categoriesdb:
    container_name: categories-db
    image: mongo
  categories:
    container_name: api-categories
    build: backend/categories/
    command: python -m flask run --host=0.0.0.0
    environment:
      - FLASK_APP=api.py
      - API_KEY=testkey
      - MONGO_URI=mongodb://categoriesdb
    ports:
      - "5001:5000"
    volumes:
      - ./backend/categories:/app/src
    depends_on:
      - categoriesdb
    links:
      - categoriesdb
  categories-test:
    container_name: api-categories-test
    build: backend/categories/
    command: /bin/sh -c "coverage run --source='.' /usr/local/bin/nosetests; coverage report -m"
    environment:
      - API_KEY=testkey
      - MONGO_URI=mongomock://localhost
    volumes:
      - ./backend/categories:/app/src
